name: Playwright E2E Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automation Repo
        uses: actions/checkout@v6
        with:
          path: automation

      - name: Checkout App Repo
        uses: actions/checkout@v6
        with:
          repository: AdhamSattawi/next-fullstack-realworld-app
          path: app

      - name: Start App Environment
        run: |
          cd app
          docker compose -f docker-compose.production.yml build
          docker compose -f docker-compose.production.yml up -d

      - name: Wait for App to be Responsive
        run: |
          echo "Waiting for Next.js to start on port 3000..."
          # This loop runs on the runner and checks 'localhost:3000' 
          # until it gets a 200 OK or 302 Redirect.
          timeout 60s sh -c 'until curl -sIL http://localhost:3000/login | grep "200\|302" > /dev/null; do echo "App is still booting..."; sleep 3; done'
          echo "App is UP and READY!"

      - name: Run Automation Tests
        run: |
          cd automation
          docker build -t automation-tests .
          
          docker run --rm --network next-realworld-prod_default --ipc=host --shm-size=1g \
            -e BASE_URL=http://realworld-prod:3000 \
            automation-tests \
            python scripts/wait_for_url.py --url http://realworld-prod:3000/login --timeout 120

          docker run --rm --network next-realworld-prod_default --ipc=host --shm-size=1g \
            -e BASE_URL=http://realworld-prod:3000 \
            automation-tests \
            pytest --base-url http://realworld-prod:3000

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: |
            automation/reports/
            automation/test-results/

      - name: Dump App Logs On Failure
        if: failure()
        run: |
          cd app
          docker compose -f docker-compose.production.yml ps
          docker compose -f docker-compose.production.yml logs --no-color --tail=300